spring:
  datasource:
    password: 
    username: postgres
    url: jdbc:postgresql://localhost:5432/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
